notice 수정, 삭제, 검색 기능 추가
Hallym-LIKELION/HallymFestival2023-Backend- pull request #37
Opened 2023-03-25 06:00 UTC by mijin0721

2023-03-25 08:12 UTC, mythpoy requested changes

2023-03-25 08:12 UTC, mythpoy commented on src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
> +    @DeleteMapping("/delete/{id}")
Delete 로 요청하였으니 url에서 /delete를 빼고 {id}만 넣어주시면 됩니다.
Restful API제작하는 방법 참고하시면 좋을거같아요!

2023-03-26 01:31 UTC, mijin0721 commented on src/main/java/com/hallym/festival/domain/notice/controller/NoticeController.java
> +    @DeleteMapping("/delete/{id}")
넵!!!

2023-03-26 03:13 UTC, mythpoy approved these changes
수고하셨습니다!

2023-03-26 03:13 UTC, merged